# minimal values for kube-prometheus-stack
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    externalLabels: {}
  service:
    type: LoadBalancer
    port: 9090

alertmanager:
  service:
    type: LoadBalancer

kubeStateMetrics:
  enabled: true

nodeExporter:
  hostRootFsMount: true
  service:
    type: ClusterIP
